USE [fenjaylabs]
GO

/****** Object:  Table [dbo].[VS_FJL_CharacterIDName]    Script Date: 7/15/2015 13:04:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[VS_FJL_CharacterIDName](
	[CharacterId] [int] NOT NULL,
	[CharacterName] [varchar](500) NOT NULL,
 CONSTRAINT [PK_VS_FJL_CharacterIDName] PRIMARY KEY CLUSTERED 
(
	[CharacterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


